### ISSUE TITLE
Addr take 1 parameter

### ISSUE THREAD

**Issue by eribol** [ryanmcgrath/jelly#1]
Sorry, this is the only way i can say my problem with your pretty example.

> pub dbs: Addr<Syn, util::database::Database>,
>    |                        ^^^^^^^^^^^^^^^^^^^^^^^^ unexpected type argument

**Comment by ryanmcgrath** [comment]
Just delete `Syn, `. `actix` doesn't require that in newer versions.

**Comment by eribol** [comment]
Thank you so much.
