### ISSUE TITLE
Validation is no have inner.

### ISSUE THREAD

**Issue by eribol** [ryanmcgrath/jelly#2]
https://github.com/ryanmcgrath/jelly/blob/master/src/util/forms.rs

> no method named `inner` found for type `validator::ValidationErrors` in the current scope

**Comment by ryanmcgrath** [comment]
:)

This isn’t an up to date build, if you haven’t noticed. It was an example repo, and modifying it to be up to date with new crates is on you. I don’t mind providing pointers, but if we could avoid opening issue after issue for it...

(Check the new validation stuff in Keats crate is my guess)

**Comment by eribol** [comment]
i noticed it but i just say it. I searched a document/article for this in your blog but did not find it. Thats why i am opened it. :)
